import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import { dir } from 'i18next';
import { locales } from '@/src/i18n/settings';
import { Footer } from './_components/Footer';
import { Locale } from '@/src/i18n';

const inter = Inter({ subsets: ['latin'] });

export async function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: Locale };
}) {
  return (
    <html lang={locale} dir={dir(locale)}>
      <body className={inter.className}>
        {children}
        <Footer locale={locale} />
      </body>
    </html>
  );
}
